"""add datetime columns back

Revision ID: 03dd06c09573
Revises: c0d579dbe1c2
Create Date: 2023-07-08 11:58:27.395699

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '03dd06c09573'
down_revision = 'c0d579dbe1c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
