"""change timezone to UTC+00:00

Revision ID: 6f61f9fc8e16
Revises: a9ce5e33e891
Create Date: 2023-07-08 11:53:43.982585

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '6f61f9fc8e16'
down_revision = 'a9ce5e33e891'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
